-- SELECT U.USER_ID
-- ,      U.NICKNAME
-- ,      TOTAL_SALES
-- FROM USED_GOODS_USER U JOIN(SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
--                             FROM USED_GOODS_BOARD
--                             WHERE STATUS = 'DONE'
--                             GROUP BY WRITER_ID) B
--                        ON WRITER_ID = USER_ID
-- WHERE TOTAL_SALES >= 700000
-- ORDER BY TOTAL_SALES;

SELECT U.USER_ID
,      U.NICKNAME
,      SUM(B.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD B 
JOIN USED_GOODS_USER U ON B.WRITER_ID = U.USER_ID
WHERE B.STATUS = 'DONE'
GROUP BY B.WRITER_ID, U.USER_ID, U.NICKNAME
HAVING SUM(B.PRICE) >= 700000
ORDER BY TOTAL_SALES;

