-- SELECT BOARD.TITLE
-- ,      BOARD.BOARD_ID
-- ,      REPLY.REPLY_ID
-- ,      REPLY.WRITER_ID
-- ,      REPLY.CONTENTS
-- ,      TO_CHAR(REPLY.CREATED_DATE, 'YYYY-MM-DD') AS CREATED_DATE
-- FROM USED_GOODS_BOARD BOARD
-- ,    USED_GOODS_REPLY REPLY
-- WHERE TO_CHAR(BOARD.CREATED_DATE, 'YYYY-MM') = '2022-10'
-- AND BOARD.BOARD_ID = REPLY.BOARD_ID
-- ORDER BY REPLY.CREATED_DATE, BOARD.TITLE;

SELECT B.TITLE
,      B.BOARD_ID
,      R.REPLY_ID
,      R.WRITER_ID
,      R.CONTENTS
,      TO_CHAR(R.CREATED_DATE, 'YYYY-MM-DD') AS CREATED_DATE
FROM USED_GOODS_BOARD B JOIN USED_GOODS_REPLY R ON B.BOARD_ID = R.BOARD_ID
WHERE TO_CHAR(B.CREATED_DATE, 'YYYY-MM') = '2022-10'
ORDER BY R.CREATED_DATE, B.TITLE;