SELECT a.PRODUCT_ID, a.PRODUCT_NAME, sum(AMOUNT * PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT a JOIN FOOD_ORDER b
    ON a.PRODUCT_ID = b.PRODUCT_ID
WHERE TO_CHAR(PRODUCE_DATE, 'YYYY-MM') = '2022-05'
GROUP BY a.PRODUCT_ID, a.PRODUCT_NAME
ORDER BY 3 DESC, 1