SELECT DISTINCT(C.CAR_ID) AS CAR_ID
FROM CAR_RENTAL_COMPANY_CAR C
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
    ON C.CAR_ID = RH.CAR_ID
WHERE C.CAR_TYPE = '세단'
AND TO_CHAR(RH.START_DATE, 'MM') = 10
ORDER BY C.CAR_ID DESC;